
configuration: Release
os: Visual Studio 2015
platform: x86

install:
    - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 14 2015"
  - cmake --build . -- /verbosity:minimal /p:Configuration=Release
  - cd ..\

notifications:

  - provider: Email
    on_build_status_changed: false
